package com.nevexis.backend.schoolManagement.email

enum class TemplateType {
    RESET_PASSWORD,
    EVALUATION_CREATE, EVALUATION_UPDATE, EVALUATION_DELETE,
    ASSIGNMENT_CREATE, ASSIGNMENT_UPDATE, ASSIGNMENT_DELETE,
}
